---

# This is the string configuration file for English.
en-GB:
  ui_unit_verbs_undo: Undo
  ui_unit_verbs_undo_turn: Undo Turn
  ui_unit_verbs_save_slot: Save
  ui_unit_verbs_load_slot: Load
  ui_unit_verbs_reposition: Reposition
  
...
