---

verbs:
  - id: undo
    icon: ui/icons/unit_action_icon_undo.png
    name: ui_unit_verbs_undo
    targetted: false
    scriptName: verbs/undo
  
  - id: undo_turn
    icon: ui/icons/unit_action_icon_undo_turn.png
    name: ui_unit_verbs_undo_turn
    targetted: false
    scriptName: verbs/undo_turn

  - id: save_slot
    icon: ui/icons/unit_action_icon_save_slot.png
    name: ui_unit_verbs_save_slot
    targetted: true
    targetColour: target
    targetOutlineColour: target_outline
    scriptName: verbs/save_slot
    
  - id: load_slot
    icon: ui/icons/unit_action_icon_load_slot.png
    name: ui_unit_verbs_load_slot
    targetted: true
    targetColour: target
    targetOutlineColour: target_outline
    scriptName: verbs/load_slot

  - id: reposition
    icon: ui/icons/unit_action_icon_reposition.png
    name: ui_unit_verbs_reposition
    targetted: true
    targetColour: target
    targetOutlineColour: target_outline
    scriptName: verbs/reposition
...
